### ISSUE TITLE
Cerrar sesión

### ISSUE THREAD

**Issue by gbandres98** [DecideIO-Cabina/decide-io-telegram#10]
**Describe la funcionalidad**
Un método muy simple. Tras elegir la opción de cerrar sesión, borraremos todos los datos del usuario (#6) y le devolveremos al menú inicial.

**Comment by Agusnez** [comment]
En verdad no funciona la llamada `logout` de la api de postprocesado. Tan solo borraremos los datos del usuario de memoria y haremos lo que has dicho.
