### ISSUE TITLE
Despliegue en Heroku

### ISSUE THREAD

**Issue by gbandres98** [DecideIO-Cabina/decide-io-telegram#12]
**Describe la funcionalidad**
Hay que completar el flujo de Travis para que despliegue la aplicación en Heroku automáticamente.

**Información adicional**
Es importante que solo se despliegue la rama master, ya que es la rama donde se encuentra la versión estable y lista para producción de la aplicación.

**Comment by Agusnez** [comment]
@gbandres98 Hay un problema. Y es que el bot que usamos para desarrollar está enlazado a la cuenta principal. Si subimos a Heroku el bot ¿habrá conflictos cuando corramos el bot en nuestro local? Supongo que sí.

**Comment by gbandres98** [comment]
Tienes razón, la solución que se me ocurre es:

1. Registrar otro bot en Telegram
2. Mover el código que identifica el bot a las propiedades de Spring (application.properties)
3. Configurar la aplicación y el despliegue para que al desplegar en Heroku se use un perfil de "producción" y este perfil haga que se carguen las propiedades del fichero application-prod.properties con otro código diferente al de desarrollo

Spring hace casi todo eso por defecto, sobre todo hay que ver cómo configurar el despliegue.

**Comment by Agusnez** [comment]
Por ahora vamos a optar por poner Heroku en modo mantenimiento cuando se quiera desarrollar.
