### ISSUE TITLE
Obtener la lista de votaciones disponibles para el usuario

### ISSUE THREAD

**Issue by gbandres98** [DecideIO-Cabina/decide-io-telegram#8]
**Describe la funcionalidad**
Hay que darle al usuario logeado la opción de ver las votaciones en las que puede participar. Para eso, el grupo de DecideIO-Censo va a implementar un método que nos devuelve estas votaciones según el Token del usuario autenticado.

Se recomienda presentar la lista de votaciones con [Inline Keyboard](https://core.telegram.org/bots#inline-keyboards-and-on-the-fly-updating).

Elegir una votación debe llevar al usuario al método implementado en #9.

**Información adicional**
Hasta que DecideIO-Censo implemente el método, hay que hacer un método que devuelva una respuesta de prueba. El resto de esta funcionalidad tiene que estar implementado al completo, listo para utilizar el servicio de DecideIO-Censo cuando esté disponible.

Ver el estado de su issue [aquí](https://github.com/DECIDEIO-CENSO/decideio-censo/issues/9).

**Comment by gbandres98** [comment]
DecideIO-Censo ya ha implementado el método, no es exactamente como le pedimos así que habrá que hacer una segunda llamada a la API de voting para recuperar el nombre de las votaciones.

Está explicado [aquí](https://github.com/DECIDEIO-CENSO/decideio-censo/issues/9#issuecomment-453157007)

**Comment by JorgeManuelMolina** [comment]
Se ha corregido algunos fallos pero sigue fallando la accion
